version: '3'

services:
  mysql:
    image: mysql:8.3.0
    container_name: toby-mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${HOST_PORT}:3306"
  #    volumes:
  #      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.2.4
    container_name: toby-redis-container
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"

#volumes:
#  mysql_data: